[[main]]
  identifier = 'about'
  name = 'About'
  pageRef = '/about'
  weight = 10

[[main]]
  identifier = 'experience'
  name = 'Experience'
  pageRef = '/experience'
  weight = 20

[[main]]
  identifier = 'projects'
  name = 'Projects'
  pageRef = '/projects'
  weight = 30

[[main]]
  identifier = 'education'
  name = 'Education'
  pageRef = '/education'
  weight = 40

[[main]]
  identifier = 'blog'
  name = 'Blog'
  pageRef = '/blog'
  weight = 50

[[main]]
  identifier = 'resume'
  name = 'Resume'
  pageRef = '/resume'
  weight = 60

[[main]]
  identifier = 'search'
  name = 'Search'
  pageRef = '/search'
  weight = 70
